### ISSUE TITLE
Readme links to docs 404

### ISSUE THREAD

**Issue by trysenga** [atc-net/atc-rest-api-generator#180]
**Describe the bug**
The links to docs and extended are both dead links in the readme

**To Reproduce**
1. Go to readme
2. Click on 'References' or 'References Extended'
3. Error 404

**Expected behavior**
These links should navigate to a valid page (or be removed if there are not additional docs now for some reason

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by davidkallesen** [comment]
Thx, for the headsup.... we will fixit :-)
