### ISSUE TITLE
Generated projects don't have authorization enabled

### ISSUE THREAD

**Issue by trysenga** [atc-net/atc-rest-api-generator#181]
**Describe the bug**
If you take the YAML file from the sample in the repo and generate a new solution, it does not produce the same code as in the repo. Mainly I'm seeing that authentication isn't enabled. There is no authorize in the upper right on swagger. For this project, I'm needing to configure the API to use JWT but before I can even try that, I need it to generate code with authorization enabled. I see in the YAML that authorization is indicated so I'm not sure why it isn't generating it now.

**To Reproduce**
1. Take ApiSpefication.Yaml from sample in repo
2. Use atc-rest-api-generator to build a sample project from this file in a different folder
3. comment out line of code allowing anonymous usage
4. Build and run new solution 
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Here is the options JSON I used when generating to see if it would make a difference:

{
  "Generator": {
    "useAuthorization": true,
    "UseRestExtended": true,
    "Request": {
    },
    "Response": {
      "UseProblemDetailsAsDefaultBody": true
    }
  },
	"Validation": {
		"StrictMode": false,
		"OperationIdCasingStyle": "CamelCase",
		"ModelNameCasingStyle": "PascalCase",
		"ModelPropertyNameCasingStyle": "CamelCase"
	}
}

**Comment by davidkallesen** [comment]
Thx, for the headsup.... we will fix it soon :-)

**Comment by trysenga** [comment]
I love the work you've done here. I really want to steer my team to use this to free them up from the grind to focus more on creative problem solving areas.

**Comment by perkops** [comment]
Hi @trysenga 

In the Demo API, we have manually create a Demo.Api.Full project to showcase how to add SwaggerUI Authorization to the scaffolded API project.

The thing missing from the scaffolded API to get the [Authorize] button in the Swagger UI is a configuration of Swagger Options.

You can see the demo implementation here: https://github.com/atc-net/atc-rest-api-generator/blob/main/sample/src/Demo.Api.Full/ConfigureSwaggerOptions.cs
And its being wired up here: https://github.com/atc-net/atc-rest-api-generator/blob/main/sample/src/Demo.Api.Full/Startup.cs

In the Demo.Api.Full Startup.cs class you can also see an example of the RestApiExtendedOptions available to set to configure the API. (E.g. there is a filter to bypass all authorization set up, so no security being applied when testing locally)

The reason for not automatically generating the SwaggerOptions are that there are so many possible implementations, and we have no idea how someone would go about on implementing this or what their individual needs would be.

It could be various:
	Authentication Mechanisms (APIKey, Basic, OAuth, OpenId)
	Flows (implicit, authorizationCode+pkce etc)
	Identity providers (IdP) e.g. Azure AD, Azure AD B2C.
	
So for now - try to implement the ConfigureSwaggerOptions class and wire it up to play around with it.
Once confident with this, depending on your needs theres tons of articles/content available online on how to specifically setting up your IdP in the API and in Swagger.

If you have any more questions, please do feel free to reach out and we will do our best to help you get onboarded.

**Comment by trysenga** [comment]
I will try that (swagger). I suppose I also wasn't clear enough. When I used swagger to hit the endpoint addresses, it came back with unimplemented rather than unauthorized. But now that I double check, the demo from the repo also does not force authorization. So there is something remaining to be added to enforce authorization. I tried moving over our add authorization to the startup but get a runtime error saying bearer is already defined/added.

Tobin

**Comment by perkops** [comment]
> 

Hi Tobin,

We just tested locally here and it works fine.

If we set AllowAnonymousAccessForDevelopment to true, 501 is returned as expected, since the API Domain handler is not implemented (thats up to the developer :) ).

If we set AllowAnonymousAccessForDevelopment to false, 401 is returned as expected.

No swagger authorization in effect - and no additional code added.

Would be happy to look at your code, if you could upload it zipped somewhere.

Btw. AddAuthentication (JWT) is already to the api in the extension method you can see here:

![image](https://github.com/atc-net/atc-rest-api-generator/assets/43060445/134fe8e7-7537-4d8a-88bc-7e76bcb043fc)

If you want your own authorize scheme added, you can "null" the existing via options:

restApiOptions = new RestApiExtendedOptions
        {
            AllowAnonymousAccessForDevelopment = true,
            EnableRequestResponseLogger = true,
            Authorization = null, // To disable existing auth wire-up
        };

**Comment by perkops** [comment]
Closing issue for now - feel free to re-open, if the need arises.
