### ISSUE TITLE
Generator does not honor the "pattern" from a property

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-rest-api-generator#61]
**Describe the bug**
Generator does not honor the "pattern" from a property, and hence does not produce a RegularExpression attribute on a parameter/request property.

Given this yaml:
![image](https://user-images.githubusercontent.com/43060445/105855172-12f48c00-5fe8-11eb-9526-dd78bfa77d74.png)

The following is generated:

        [Required]
        [MinLength(2)]
        [MaxLength(2)]
        public string Alpha2Code { get; set; }

However, this should be generated:

        [Required]
        [MinLength(2)]
        [MaxLength(2)]
        [RegularExpression("^[A-Z]$")]
        public string Alpha2Code { get; set; }

**Comment by egil** [comment]
I am working on this!
