### ISSUE TITLE
Swagger UI: RoutePatternException

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-rest-api-generator#90]
**Describe the bug**
Swagger UI cannot start up and a RoutePatternException is thrown: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.

**Expected behavior**
Swagger UI should load.

**Scenario**
Happens if the spec file differs from:

servers:
  - url: 'api/v1'

**Suggestion**
Make spec validation of that part.

**Comment by davidkallesen** [comment]
The 'bug' is just a missing validation for `server/url` start path.
Example on vaild yaml:
```yaml
server:
  - url: api/v1
``` 
Example on invaild yaml:
```yaml
servers:
  - url: /v1
```
